image: archlinux
packages:
  - nodejs
  - yarn
environment:
  build_env: production
  project: maxleiter.com
sources:
  - https://github.com/MaxLeiter/maxleiter.com
tasks:
  - prepare: |
      cd ${project}
      yarn
  - test: |
      cd ${project}
      yarn prettier
      yarn build
